### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by jhsc** [steffen25/golang.zone#35]
Hello I'm the person who wanted to help "Dockerize" the app but I have a... What tool did you use to create and migrate the database?

**Comment by steffen25** [comment]
Hey @jhsc unfortunately everything is done by hand.. what does that mean? Well because it was my first project in Go I wanted to minimize the use of third party libs..  I would say gorm would be a good choice also what I have heard from others by the way I actually pushed my docker setup yesterday it has a sql dump of the current database inside.

https://github.com/steffen25/golang.zone/tree/feature/docker_setup 
Sorry that I havent added any documentation about it

Here is a draft version

1. cd to the project workspace and build the image
docker build -t golang-zone-api .
2. create the config file in config/app.json matching the mysql settings then compile the binary (I guess this step could be done in a smarter way)
env GOOS=linux GOARCH=386 go build -o api
3. docker-compose up
4. the api is now live at localhost:8080


Do you have any preferences when it comes to migrations?

**Comment by jhsc** [comment]
I think a good solution to migrate in go is to use https://github.com/pressly/goose.

When I finish my work I will show you in the pull request how to create and migrate the database using goose library.

**Comment by steffen25** [comment]
Hey goose look like the right tool for the job 👍
Thanks for investing your time in this

**Comment by steffen25** [comment]
@jhsc The db/dbconf.yml should be added to .gitignore I guess? Second, isnt there a way it could be read from the config/app.json? It seems stupid to have to remember you have to edit it in two places instead of one.

Another question is the passwords in the docker-compose.yml what about those? Do you just edit them locally and then build the image then docker-compose up? I had another issue just a minute ago I ran docker-compose up and everything worked then I wanted to change the mysql user, password then the mysql container gave me this error Access denied for user bla bla.. fine I found out it has to do with the volume it is mounting so what I did was "docker volume rm golangzone_app_mysql_data" this is probably just me doing something in the wrong order? I guess since I didnt ran with the --rm option it didnt delete the volumes  golangzone_app_mysql_data, and the other two right? 

First time using docker for a real project 😄  so bear with me.

**Comment by steffen25** [comment]
@jhsc Hey could you answer my questions above? Thanks 👍

**Comment by jhsc** [comment]
So I added config/dbconf.yml to help with goose migrations, but their documentation is sort of lacking how to get it working properly because I always had to type the db/user/password from the command line. So I'm thinking of adding gorm library to help with the database migrations and database driver(Next pull request will include this solution) and all together replace goose.

To answer second question the best solution when dealing with docker is to have separate docker-compose files for every environment... say for example if we had a production compose file we would list all our services and use a compose command to load a separate .env  file (which we would gitignore). 

Yes thats a volume discrepancy, since in our docker-compose file we set MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD the image created a database owned by the user (https://hub.docker.com/_/mysql/) and we keep reusing that volume (app_mysql_data).

**Comment by steffen25** [comment]
Hey @jhsc  thanks, yes I think gorm will be a better choice :) Do you have discord, slack channel or something where I can chat with you?

**Comment by jhsc** [comment]
No I don't but if you want create a slack channel and I'll join.

**Comment by steffen25** [comment]
@jhsc Are you on the gophers slack channel? https://gophers.slack.com 

Invite link: https://invite.slack.golangbridge.org
